auto enable webhook
razorpay/razorpay-woocommerce pull request #249
Opened 2022-04-08 03:59 UTC by jampulanaveen

2022-04-11 11:47 UTC, ChetanGN commented on woo-razorpay.php
> +            $TimeNow = new DateTime('now');
@jampulanaveen Make it camelcase.

2022-04-11 11:48 UTC, ChetanGN commented on woo-razorpay.php
> +            if(empty($getWebhookFlag)){
@jampulanaveen Maintain code format.

2022-04-11 11:54 UTC, ChetanGN commented on woo-razorpay.php
> +
Remove blank space

2022-04-22 04:51 UTC, ramth05 commented on woo-razorpay.php
> +                $hours = ($interval->days * 24) + $interval->h;
@jampulanaveen, We don't needs hours conversion here, just use time stamp + 24 hours ( in seconds) for comparision.

2022-04-22 04:52 UTC, ramth05 commented on woo-razorpay.php
> +            $secret      =  bin2hex(openssl_random_pseudo_bytes(4));
@jampulanaveen Can we use bugger length secrets here also if it must have capital, small case letters and numbers.

2022-04-22 04:53 UTC, ramth05 requested changes
@jampulanaveen , don't see any list for the supported events.

2022-04-22 05:03 UTC, ramth05 commented on woo-razorpay.php
> +
@jampulanaveen , remove items from $visibleSettings list.

2022-04-22 06:39 UTC, ramth05 commented
@jampulanaveen , please verify if how we are going to handle subscription based events in this.

2022-05-06 09:59 UTC, ramth05 commented on woo-razorpay.php
> +                        foreach($value['events'] as $evntkey => $evntval)
space before `(`

2022-05-06 09:59 UTC, ramth05 commented on woo-razorpay.php
> +           if(!empty($getWebhookFlag)){
start it with new line `{`

2022-05-06 12:52 UTC, jampulanaveen commented on woo-razorpay.php
> +                if($getWebhookFlag + 86400 < time()){
done

2022-05-06 12:53 UTC, jampulanaveen commented on woo-razorpay.php
> +           if(!empty($getWebhookFlag)){
done, ok

2022-05-06 12:53 UTC, jampulanaveen commented on woo-razorpay.php
> +                        foreach($value['events'] as $evntkey => $evntval)
done

2022-05-09 06:25 UTC, ramth05 commented on woo-razorpay.php
> +            'payment.authorized',
@jampulanaveen , missing current supported events?

2022-05-10 09:26 UTC, nikhilsharma1100 approved these changes
LGTM

2022-05-10 10:20 UTC, jampulanaveen commented on woo-razorpay.php
> +            'payment.authorized',
updated

2022-05-10 10:43 UTC, merged